finished account check function
EOSTestMonster/eostestmonster pull request #6
Opened 2018-06-22 08:27 UTC by GiggleAll

finished account check function and add the function of httpapi, convenient to write testcase to call the main chain of some information.
And I have tested the httpapi function, it run well.
Usecase write in httpapi.README.md

2018-06-26 09:03 UTC, EOSBIXIN commented on eosapi/httpapi/client.py
> +    # client.get_info()
please remove comments and give a detail description in Readme file

2018-06-26 09:11 UTC, EOSBIXIN commented on eosapi/httpapi/README.md
> +
we should move the basic Client description into ../../README.md file, so others will see how to use the tool

2018-06-26 09:14 UTC, EOSBIXIN commented on eosapi/httpapi/http_client.py
> +logger = logging.getLogger(__name__)
we should the same logs/logger, avoid to defined duplicate log

2018-06-26 09:17 UTC, EOSBIXIN commented on startmonster.py
> +    # TODO but by this way you need run this program in your nodeos server
maybe we can remove the TODO comments

2018-06-26 09:19 UTC, EOSBIXIN requested changes
thanks for the basic tool, adjust more pls.

2018-06-28 03:15 UTC, GiggleAll commented
I have cleaned up the code and unified log, and modified readme(en), and I tested startmonster, it worked well.

2018-06-29 04:19 UTC, merged